/* The following code was generated by JFlex 1.6.1 */

package org.fife.ui.rsyntaxtextarea.modes;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;
   

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Timothy Marcoe/FetalIDE Archive/Fetal IDE/src/org/fife/ui/rsyntaxtextarea/modes/FetalJFlexTokenMaker.flex</tt>
 */
public class FetalJFlexTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MLC = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\5\1\11\1\12\1\10\22\0\1\6\1\71\1\7"+
    "\1\0\1\0\1\64\1\66\1\4\2\15\1\14\1\64\1\4\1\64"+
    "\1\16\1\13\12\2\1\72\1\4\1\64\1\65\1\70\1\4\1\0"+
    "\1\1\1\26\1\1\1\37\1\1\1\54\1\1\1\42\4\1\1\44"+
    "\1\60\1\45\3\1\1\62\1\34\1\56\1\32\1\50\1\1\1\52"+
    "\1\1\1\15\1\3\1\15\1\67\1\1\1\0\1\27\1\17\1\31"+
    "\1\24\1\20\1\46\1\21\1\47\1\22\1\63\1\51\1\30\1\53"+
    "\1\23\1\41\1\36\1\1\1\33\1\40\1\25\1\43\1\55\1\57"+
    "\1\61\1\35\1\1\1\15\1\73\1\15\1\4\6\0\1\11\u1fa2\0"+
    "\1\11\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\5\2\6\1\7"+
    "\21\1\4\6\1\1\1\6\1\10\1\11\1\10\1\0"+
    "\1\12\2\5\1\13\1\14\1\15\6\1\1\16\26\1"+
    "\1\17\1\20\1\21\16\1\1\22\77\1\1\16\75\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\170\0\u012c\0\u0168"+
    "\0\u01a4\0\u01e0\0\170\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c"+
    "\0\u0348\0\u0384\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec"+
    "\0\u0528\0\u0564\0\u05a0\0\u05dc\0\u0618\0\u0654\0\u0690\0\170"+
    "\0\u01e0\0\u06cc\0\u0708\0\170\0\u0744\0\u0780\0\u07bc\0\u07f8"+
    "\0\u0834\0\170\0\u0870\0\170\0\u08ac\0\u08e8\0\u0924\0\u0960"+
    "\0\u099c\0\u09d8\0\264\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04"+
    "\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4"+
    "\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4"+
    "\0\u0f00\0\170\0\u0f3c\0\170\0\u0f78\0\u0fb4\0\u0ff0\0\u102c"+
    "\0\u1068\0\u10a4\0\u10e0\0\u111c\0\u1158\0\u1194\0\u11d0\0\u120c"+
    "\0\u1248\0\u1284\0\264\0\u12c0\0\u12fc\0\u1338\0\u1374\0\u13b0"+
    "\0\u13ec\0\u1428\0\u1464\0\u14a0\0\u14dc\0\u1518\0\u1554\0\u1590"+
    "\0\u15cc\0\u1608\0\u1644\0\u1680\0\u16bc\0\u16f8\0\u1734\0\u1770"+
    "\0\u17ac\0\u17e8\0\u1824\0\u1860\0\u189c\0\u18d8\0\u1914\0\u1950"+
    "\0\u198c\0\u19c8\0\u1a04\0\u1a40\0\u1a7c\0\u1ab8\0\u1af4\0\u1b30"+
    "\0\u1b6c\0\u1ba8\0\u1be4\0\u1c20\0\u1c5c\0\u1c98\0\u1cd4\0\u1d10"+
    "\0\u1d4c\0\u1d88\0\u1dc4\0\u1e00\0\u1e3c\0\u1e78\0\u1eb4\0\u1ef0"+
    "\0\u1f2c\0\u1f68\0\u1fa4\0\u1fe0\0\u201c\0\u2058\0\u2094\0\u20d0"+
    "\0\u210c\0\u2148\0\u2184\0\u21c0\0\u21fc\0\u2238\0\u2274\0\u22b0"+
    "\0\u22ec\0\u2328\0\u2364\0\u23a0\0\u23dc\0\u2418\0\u2454\0\u2490"+
    "\0\u24cc\0\u2508\0\u2544\0\u2580\0\u25bc\0\u25f8\0\u2634\0\u2670"+
    "\0\u26ac\0\u26e8\0\u2724\0\u2760\0\u279c\0\u27d8\0\u2814\0\u2850"+
    "\0\u288c\0\u28c8\0\u2904\0\u2940\0\u297c\0\u29b8\0\u29f4\0\u2a30"+
    "\0\u2a6c\0\u2aa8\0\u2ae4\0\u2b20\0\u2b5c\0\u2b98\0\u2bd4\0\u2c10"+
    "\0\u2c4c\0\u2c88\0\u2cc4\0\u2d00\0\u2d3c\0\u2d78\0\u2db4\0\u2df0"+
    "\0\u2e2c\0\u2e68\0\u2ea4\0\u2ee0\0\u2f1c\0\u2f58\0\u2f94\0\u2fd0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\2\3\1\6\1\7\1\10\2\0"+
    "\1\7\1\11\1\12\1\13\1\3\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\4\1\23\1\24\1\25"+
    "\1\4\1\26\2\4\1\27\1\4\1\30\1\31\1\4"+
    "\1\32\2\4\1\33\4\4\1\34\10\4\1\12\1\35"+
    "\1\36\1\37\1\40\1\41\1\40\1\42\5\43\1\44"+
    "\6\43\1\45\57\43\75\0\2\4\13\0\1\46\45\4"+
    "\10\0\2\47\1\5\1\47\5\0\1\47\5\0\45\47"+
    "\16\0\1\7\3\0\1\7\61\0\3\10\1\50\1\10"+
    "\1\51\1\10\1\52\64\10\13\0\1\53\1\54\50\0"+
    "\1\40\73\0\1\40\7\0\2\4\13\0\1\46\1\4"+
    "\1\55\20\4\1\56\22\4\11\0\2\4\13\0\1\46"+
    "\4\4\1\57\4\4\1\60\33\4\11\0\2\4\13\0"+
    "\1\46\1\4\1\61\43\4\11\0\2\4\13\0\1\46"+
    "\4\4\1\62\22\4\1\63\4\4\1\64\10\4\11\0"+
    "\2\4\13\0\1\46\1\4\1\65\22\4\1\66\20\4"+
    "\11\0\2\4\13\0\1\46\1\4\1\67\6\4\1\70"+
    "\34\4\11\0\2\4\13\0\1\46\14\4\1\71\5\4"+
    "\1\72\22\4\11\0\2\4\13\0\1\46\1\73\10\4"+
    "\1\74\33\4\11\0\2\4\13\0\1\46\1\4\1\75"+
    "\1\4\1\76\16\4\1\77\22\4\11\0\2\4\13\0"+
    "\1\46\14\4\1\100\5\4\1\101\22\4\11\0\2\4"+
    "\13\0\1\46\22\4\1\102\22\4\11\0\2\4\13\0"+
    "\1\46\14\4\1\103\21\4\1\63\6\4\11\0\2\4"+
    "\13\0\1\46\6\4\1\104\36\4\11\0\2\4\13\0"+
    "\1\46\1\105\44\4\11\0\2\4\13\0\1\46\17\4"+
    "\1\106\25\4\11\0\2\4\13\0\1\46\10\4\1\107"+
    "\25\4\1\63\6\4\11\0\2\4\13\0\1\46\1\4"+
    "\1\110\6\4\1\111\34\4\75\0\1\40\2\0\1\40"+
    "\71\0\1\40\72\0\1\40\1\0\1\40\77\0\1\40"+
    "\5\43\1\0\6\43\1\0\57\43\13\0\1\112\61\0"+
    "\1\113\15\0\45\113\10\0\4\47\5\0\1\47\5\0"+
    "\45\47\10\0\5\51\1\0\2\51\3\0\64\51\1\50"+
    "\3\51\1\114\64\51\5\53\1\0\2\53\3\0\61\53"+
    "\1\0\2\4\13\0\1\46\2\4\1\115\42\4\11\0"+
    "\2\4\13\0\1\46\22\4\1\116\22\4\11\0\2\4"+
    "\13\0\1\46\5\4\1\63\37\4\11\0\2\4\13\0"+
    "\1\46\21\4\1\117\23\4\11\0\2\4\13\0\1\46"+
    "\6\4\1\120\36\4\11\0\2\4\13\0\1\46\21\4"+
    "\1\121\23\4\11\0\2\4\13\0\1\46\17\4\1\122"+
    "\25\4\11\0\2\4\13\0\1\46\42\4\1\123\2\4"+
    "\11\0\2\4\13\0\1\46\34\4\1\124\10\4\11\0"+
    "\2\4\13\0\1\46\1\125\10\4\1\126\1\127\4\4"+
    "\1\130\25\4\11\0\2\4\13\0\1\46\6\4\1\131"+
    "\7\4\1\132\3\4\1\133\22\4\11\0\2\4\13\0"+
    "\1\46\24\4\1\134\20\4\11\0\2\4\13\0\1\46"+
    "\5\4\1\135\37\4\11\0\2\4\13\0\1\46\21\4"+
    "\1\136\23\4\11\0\2\4\13\0\1\46\3\4\1\137"+
    "\41\4\11\0\2\4\13\0\1\46\5\4\1\140\37\4"+
    "\11\0\2\4\13\0\1\46\21\4\1\141\23\4\11\0"+
    "\2\4\13\0\1\46\22\4\1\142\22\4\11\0\2\4"+
    "\13\0\1\46\1\4\1\143\43\4\11\0\2\4\13\0"+
    "\1\46\34\4\1\144\10\4\11\0\2\4\13\0\1\46"+
    "\24\4\1\145\20\4\11\0\2\4\13\0\1\46\3\4"+
    "\1\146\41\4\11\0\2\4\13\0\1\46\14\4\1\147"+
    "\30\4\11\0\2\4\13\0\1\46\44\4\1\150\11\0"+
    "\2\4\13\0\1\46\5\4\1\151\37\4\11\0\2\4"+
    "\13\0\1\46\11\4\1\60\33\4\11\0\2\4\13\0"+
    "\1\46\14\4\1\152\30\4\11\0\2\4\13\0\1\46"+
    "\17\4\1\153\25\4\11\0\2\113\14\0\45\113\11\0"+
    "\2\4\13\0\1\46\3\4\1\154\41\4\11\0\2\4"+
    "\13\0\1\46\11\4\1\155\33\4\11\0\2\4\13\0"+
    "\1\46\1\4\1\63\43\4\11\0\2\4\13\0\1\46"+
    "\7\4\1\156\3\4\1\157\4\4\1\160\2\4\1\161"+
    "\1\4\1\162\5\4\1\163\11\4\11\0\2\4\13\0"+
    "\1\46\1\4\1\164\43\4\11\0\2\4\13\0\1\46"+
    "\22\4\1\164\22\4\11\0\2\4\13\0\1\46\6\4"+
    "\1\165\36\4\11\0\2\4\13\0\1\46\1\166\44\4"+
    "\11\0\2\4\13\0\1\46\3\4\1\141\41\4\11\0"+
    "\2\4\13\0\1\46\1\4\1\167\43\4\11\0\2\4"+
    "\13\0\1\46\3\4\1\170\41\4\11\0\2\4\13\0"+
    "\1\46\11\4\1\171\33\4\11\0\2\4\13\0\1\46"+
    "\1\4\1\133\43\4\11\0\2\4\13\0\1\46\26\4"+
    "\1\172\16\4\11\0\2\4\13\0\1\46\1\4\1\63"+
    "\2\4\1\173\40\4\11\0\2\4\13\0\1\46\10\4"+
    "\1\174\34\4\11\0\2\4\13\0\1\46\20\4\1\175"+
    "\20\4\1\176\3\4\11\0\2\4\13\0\1\46\10\4"+
    "\1\177\34\4\11\0\2\4\13\0\1\46\2\4\1\200"+
    "\42\4\11\0\2\4\13\0\1\46\6\4\1\63\36\4"+
    "\11\0\2\4\13\0\1\46\32\4\1\201\12\4\11\0"+
    "\2\4\13\0\1\46\5\4\1\125\37\4\11\0\2\4"+
    "\13\0\1\46\34\4\1\202\10\4\11\0\2\4\13\0"+
    "\1\46\4\4\1\203\40\4\11\0\2\4\13\0\1\46"+
    "\4\4\1\141\40\4\11\0\2\4\13\0\1\46\3\4"+
    "\1\204\41\4\11\0\2\4\13\0\1\46\1\4\1\205"+
    "\43\4\11\0\2\4\13\0\1\46\10\4\1\167\34\4"+
    "\11\0\2\4\13\0\1\46\2\4\1\117\42\4\11\0"+
    "\2\4\13\0\1\46\35\4\1\206\7\4\11\0\2\4"+
    "\13\0\1\46\4\4\1\63\40\4\11\0\2\4\13\0"+
    "\1\46\1\4\1\207\43\4\11\0\2\4\13\0\1\46"+
    "\10\4\1\210\11\4\1\211\22\4\11\0\2\4\13\0"+
    "\1\46\10\4\1\212\34\4\11\0\2\4\13\0\1\46"+
    "\1\4\1\213\6\4\1\214\34\4\11\0\2\4\13\0"+
    "\1\46\22\4\1\215\22\4\11\0\2\4\13\0\1\46"+
    "\3\4\1\216\16\4\1\217\22\4\11\0\2\4\13\0"+
    "\1\46\1\4\1\220\43\4\11\0\2\4\13\0\1\46"+
    "\14\4\1\141\30\4\11\0\2\4\13\0\1\46\20\4"+
    "\1\151\24\4\11\0\2\4\13\0\1\46\1\4\1\221"+
    "\43\4\11\0\2\4\13\0\1\46\6\4\1\117\36\4"+
    "\11\0\2\4\13\0\1\46\34\4\1\222\10\4\11\0"+
    "\2\4\13\0\1\46\1\4\1\223\43\4\11\0\2\4"+
    "\13\0\1\46\27\4\1\224\15\4\11\0\2\4\13\0"+
    "\1\46\12\4\1\225\32\4\11\0\2\4\13\0\1\46"+
    "\16\4\1\63\26\4\11\0\2\4\13\0\1\46\1\4"+
    "\1\226\43\4\11\0\2\4\13\0\1\46\24\4\1\227"+
    "\20\4\11\0\2\4\13\0\1\46\21\4\1\63\23\4"+
    "\11\0\2\4\13\0\1\46\1\4\1\230\43\4\11\0"+
    "\2\4\13\0\1\46\24\4\1\231\20\4\11\0\2\4"+
    "\13\0\1\46\3\4\1\232\41\4\11\0\2\4\13\0"+
    "\1\46\5\4\1\233\37\4\11\0\2\4\13\0\1\46"+
    "\4\4\1\234\40\4\11\0\2\4\13\0\1\46\12\4"+
    "\1\235\32\4\11\0\2\4\13\0\1\46\3\4\1\236"+
    "\41\4\11\0\2\4\13\0\1\46\10\4\1\237\34\4"+
    "\11\0\2\4\13\0\1\46\11\4\1\240\33\4\11\0"+
    "\2\4\13\0\1\46\22\4\1\241\22\4\11\0\2\4"+
    "\13\0\1\46\14\4\1\242\30\4\11\0\2\4\13\0"+
    "\1\46\21\4\1\243\23\4\11\0\2\4\13\0\1\46"+
    "\6\4\1\117\7\4\1\177\26\4\11\0\2\4\13\0"+
    "\1\46\24\4\1\244\20\4\11\0\2\4\13\0\1\46"+
    "\4\4\1\245\40\4\11\0\2\4\13\0\1\46\4\4"+
    "\1\246\40\4\11\0\2\4\13\0\1\46\10\4\1\230"+
    "\34\4\11\0\2\4\13\0\1\46\14\4\1\133\30\4"+
    "\11\0\2\4\13\0\1\46\10\4\1\247\34\4\11\0"+
    "\2\4\13\0\1\46\6\4\1\250\36\4\11\0\2\4"+
    "\13\0\1\46\15\4\1\251\27\4\11\0\2\4\13\0"+
    "\1\46\10\4\1\252\34\4\11\0\2\4\13\0\1\46"+
    "\12\4\1\253\32\4\11\0\2\4\13\0\1\46\34\4"+
    "\1\254\10\4\11\0\2\4\13\0\1\46\14\4\1\63"+
    "\30\4\11\0\2\4\13\0\1\46\17\4\1\63\25\4"+
    "\11\0\2\4\13\0\1\46\6\4\1\255\36\4\11\0"+
    "\2\4\13\0\1\46\15\4\1\256\2\4\1\257\16\4"+
    "\1\231\5\4\11\0\2\4\13\0\1\46\2\4\1\133"+
    "\42\4\11\0\2\4\13\0\1\46\6\4\1\133\36\4"+
    "\11\0\2\4\13\0\1\46\11\4\1\117\33\4\11\0"+
    "\2\4\13\0\1\46\4\4\1\133\40\4\11\0\2\4"+
    "\13\0\1\46\10\4\1\260\34\4\11\0\2\4\13\0"+
    "\1\46\32\4\1\261\12\4\11\0\2\4\13\0\1\46"+
    "\3\4\1\262\41\4\11\0\2\4\13\0\1\46\12\4"+
    "\1\263\32\4\11\0\2\4\13\0\1\46\14\4\1\177"+
    "\30\4\11\0\2\4\13\0\1\46\24\4\1\264\20\4"+
    "\11\0\2\4\13\0\1\46\6\4\1\265\36\4\11\0"+
    "\2\4\13\0\1\46\11\4\1\133\33\4\11\0\2\4"+
    "\13\0\1\46\1\4\1\255\43\4\11\0\2\4\13\0"+
    "\1\46\30\4\1\266\14\4\11\0\2\4\13\0\1\46"+
    "\6\4\1\267\36\4\11\0\2\4\13\0\1\46\3\4"+
    "\1\270\41\4\11\0\2\4\13\0\1\46\1\4\1\271"+
    "\43\4\11\0\2\4\13\0\1\46\43\4\1\272\1\4"+
    "\11\0\2\4\13\0\1\46\22\4\1\63\22\4\11\0"+
    "\2\4\13\0\1\46\22\4\1\273\22\4\11\0\2\4"+
    "\13\0\1\46\4\4\1\274\40\4\11\0\2\4\13\0"+
    "\1\46\13\4\1\275\31\4\11\0\2\4\13\0\1\46"+
    "\10\4\1\276\34\4\11\0\2\4\13\0\1\46\14\4"+
    "\1\277\30\4\11\0\2\4\13\0\1\46\6\4\1\300"+
    "\36\4\11\0\2\4\13\0\1\46\30\4\1\63\14\4"+
    "\11\0\2\4\13\0\1\46\1\4\1\301\43\4\11\0"+
    "\2\4\13\0\1\46\1\4\1\302\43\4\11\0\2\4"+
    "\13\0\1\46\34\4\1\303\10\4\11\0\2\4\13\0"+
    "\1\46\14\4\1\304\30\4\11\0\2\4\13\0\1\46"+
    "\6\4\1\305\36\4\11\0\2\4\13\0\1\46\40\4"+
    "\1\154\4\4\11\0\2\4\13\0\1\46\12\4\1\117"+
    "\32\4\11\0\2\4\13\0\1\46\10\4\1\306\34\4"+
    "\11\0\2\4\13\0\1\46\1\307\44\4\11\0\2\4"+
    "\13\0\1\46\3\4\1\310\41\4\11\0\2\4\13\0"+
    "\1\46\1\4\1\177\43\4\11\0\2\4\13\0\1\46"+
    "\31\4\1\311\13\4\11\0\2\4\13\0\1\46\15\4"+
    "\1\312\27\4\11\0\2\4\13\0\1\46\10\4\1\313"+
    "\34\4\11\0\2\4\13\0\1\46\3\4\1\314\41\4"+
    "\11\0\2\4\13\0\1\46\22\4\1\315\22\4\11\0"+
    "\2\4\13\0\1\46\11\4\1\316\33\4\11\0\2\4"+
    "\13\0\1\46\11\4\1\317\33\4\11\0\2\4\13\0"+
    "\1\46\17\4\1\320\25\4\11\0\2\4\13\0\1\46"+
    "\1\4\1\321\43\4\11\0\2\4\13\0\1\46\3\4"+
    "\1\322\41\4\11\0\2\4\13\0\1\46\11\4\1\63"+
    "\33\4\11\0\2\4\13\0\1\46\12\4\1\63\32\4"+
    "\11\0\2\4\13\0\1\46\12\4\1\323\32\4\11\0"+
    "\2\4\13\0\1\46\24\4\1\117\20\4\11\0\2\4"+
    "\13\0\1\46\1\4\1\324\43\4\11\0\2\4\13\0"+
    "\1\46\6\4\1\325\36\4\11\0\2\4\13\0\1\46"+
    "\1\4\1\323\43\4\11\0\2\4\13\0\1\46\34\4"+
    "\1\117\10\4\11\0\2\4\13\0\1\46\32\4\1\63"+
    "\12\4\11\0\2\4\13\0\1\46\15\4\1\326\27\4"+
    "\11\0\2\4\13\0\1\46\3\4\1\327\41\4\11\0"+
    "\2\4\13\0\1\46\16\4\1\330\26\4\11\0\2\4"+
    "\13\0\1\46\22\4\1\154\22\4\11\0\2\4\13\0"+
    "\1\46\17\4\1\117\25\4\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12300];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\1\11\4\1\1\11\24\1\1\11"+
    "\3\1\1\11\1\1\1\0\3\1\1\11\1\1\1\11"+
    "\35\1\1\11\1\1\1\11\214\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  

  /* user code: */
   
   /**   
    * Constructor.  This must be here because JFlex does not generate a   
    * no-parameter constructor.   
    */   
   public FetalJFlexTokenMaker() {   
   		super();
   } 
     
   public FetalJFlexTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }
  
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    */   
   private void addToken(int tokenType) {   
      addToken(zzStartRead, zzMarkedPos-1, tokenType);   
   }   
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    * @see #addHyperlinkToken(int, int, int)   
    */   
   private void addToken(int start, int end, int tokenType) {   
      int so = start + offsetShift;   
      addToken(zzBuffer, start,end, tokenType, so, false);   
   }   
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param array The character array.   
    * @param start The starting offset in the array.   
    * @param end The ending offset in the array.   
    * @param tokenType The token's type.   
    * @param startOffset The offset in the document at which this token   
    *        occurs.   
    * @param hyperlink Whether this token is a hyperlink.   
    */   
   public void addToken(char[] array, int start, int end, int tokenType,   
                  int startOffset, boolean hyperlink) {   
      super.addToken(array, start,end, tokenType, startOffset, hyperlink);   
      zzStartRead = zzMarkedPos;   
   }   
   
   /**   
    * Returns the text to place at the beginning and end of a   
    * line to "comment" it in a this programming language.   
    *   
    * @return The start and end strings to add to a line to "comment"   
    *         it out.   
    */   
   public String[] getLineCommentStartAndEnd() {   
      return new String[] { "//", null };   
   }   
   
   /**   
    * Returns the first token in the linked list of tokens generated   
    * from <code>text</code>.  This method must be implemented by   
    * subclasses so they can correctly implement syntax highlighting.   
    *   
    * @param text The text from which to get tokens.   
    * @param initialTokenType The token type we should start with.   
    * @param startOffset The offset into the document at which   
    *        <code>text</code> starts.   
    * @return The first <code>Token</code> in a linked list representing   
    *         the syntax highlighted text.   
    */   
   public Token getTokenList(Segment text, int initialTokenType, int startOffset) {   
   
      resetTokenList();   
      this.offsetShift = -text.offset + startOffset;   
   
      // Start off in the proper state.   
      int state = Token.NULL;   
      switch (initialTokenType) {   
                  case Token.COMMENT_MULTILINE:   
            state = MLC;   
            start = text.offset;   
            break;   
   
         /* No documentation comments */   
         default:   
            state = Token.NULL;   
      }   
   
      s = text;   
      try {   
         yyreset(zzReader);   
         yybegin(state);   
         return yylex();   
      } catch (IOException ioe) {   
         ioe.printStackTrace();   
         return new TokenImpl();   
      }   
   
   }   
   
   /**   
    * Refills the input buffer.   
    *   
    * @return      <code>true</code> if EOF was reached, otherwise   
    *              <code>false</code>.   
    */   
   private boolean zzRefill() {   
      return zzCurrentPos>=s.offset+s.count;   
   }   
   
   /**   
    * Resets the scanner to read from a new input stream.   
    * Does not close the old reader.   
    *   
    * All internal variables are reset, the old input stream    
    * <b>cannot</b> be reused (internal buffer is discarded and lost).   
    * Lexical state is set to <tt>YY_INITIAL</tt>.   
    *   
    * @param reader   the new input stream    
    */  
     
   public final void yyreset(Reader reader) {   
      // 's' has been updated.   
      zzBuffer = s.array;   
      /*   
       * We replaced the line below with the two below it because zzRefill   
       * no longer "refills" the buffer (since the way we do it, it's always   
       * "full" the first time through, since it points to the segment's   
       * array).  So, we assign zzEndRead here.   
       */   
      //zzStartRead = zzEndRead = s.offset;   
      zzStartRead = s.offset;   
      zzEndRead = zzStartRead + s.count - 1;   
      zzCurrentPos = zzMarkedPos = s.offset;   
      zzLexicalState = YYINITIAL;   
      zzReader = reader;   
      zzAtEOF  = false;   
   }   
   


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FetalJFlexTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 218) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
                zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 217: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 218: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { addToken(Token.IDENTIFIER);
            }
          case 19: break;
          case 2: 
            { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
            }
          case 20: break;
          case 3: 
            { addNullToken(); return firstToken;
            }
          case 21: break;
          case 4: 
            { addToken(Token.WHITESPACE);
            }
          case 22: break;
          case 5: 
            { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
            }
          case 23: break;
          case 6: 
            { addToken(Token.OPERATOR);
            }
          case 24: break;
          case 7: 
            { addToken(Token.SEPARATOR);
            }
          case 25: break;
          case 8: 
            { 
            }
          case 26: break;
          case 9: 
            { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
          case 27: break;
          case 10: 
            { addToken(Token.ERROR_NUMBER_FORMAT);
            }
          case 28: break;
          case 11: 
            { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
            }
          case 29: break;
          case 12: 
            { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
          case 30: break;
          case 13: 
            { start = zzMarkedPos-2; yybegin(MLC);
            }
          case 31: break;
          case 14: 
            { addToken(Token.RESERVED_WORD);
            }
          case 32: break;
          case 15: 
            { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
            }
          case 33: break;
          case 16: 
            { addToken(Token.FUNCTION);
            }
          case 34: break;
          case 17: 
            { addToken(Token.ERROR_STRING_DOUBLE);
            }
          case 35: break;
          case 18: 
            { addToken(Token.DATA_TYPE);
            }
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
