/* The following code was generated by JFlex 1.6.1 */

package org.fife.ui.rsyntaxtextarea.modes;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;
   

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Timothy Marcoe/FetalIDE Archive/Fetal IDE/src/org/fife/ui/rsyntaxtextarea/modes/FetalJFlexTokenMaker.flex</tt>
 */
public class FetalJFlexTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MLC = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\5\1\11\1\12\1\10\22\0\1\6\1\62\1\7"+
    "\1\0\1\0\1\55\1\57\1\4\2\15\1\14\1\55\1\4\1\55"+
    "\1\16\1\13\12\2\1\63\1\4\1\55\1\56\1\61\1\4\1\0"+
    "\1\1\1\26\1\1\1\37\1\1\1\53\6\1\1\47\1\1\1\42"+
    "\4\1\1\34\1\1\1\32\1\45\1\1\1\50\1\1\1\15\1\3"+
    "\1\15\1\60\1\1\1\0\1\27\1\17\1\31\1\24\1\20\1\43"+
    "\1\21\1\44\1\22\1\54\1\46\1\30\1\51\1\23\1\41\1\36"+
    "\1\1\1\33\1\40\1\25\1\52\3\1\1\35\1\1\1\15\1\64"+
    "\1\15\1\4\6\0\1\11\u1fa2\0\1\11\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\5\2\6\1\7"+
    "\20\1\4\6\1\1\1\6\1\10\1\11\1\10\1\0"+
    "\1\12\2\5\1\13\1\14\1\15\5\1\1\16\21\1"+
    "\1\17\1\20\1\21\12\1\1\22\111\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\152\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\152\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1"+
    "\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459"+
    "\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597\0\152\0\u01a8"+
    "\0\u05cc\0\u0601\0\152\0\u0636\0\u066b\0\u06a0\0\u06d5\0\u070a"+
    "\0\152\0\u073f\0\152\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848"+
    "\0\237\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb"+
    "\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63"+
    "\0\u0b98\0\u0bcd\0\152\0\u0c02\0\152\0\u0c37\0\u0c6c\0\u0ca1"+
    "\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\237"+
    "\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc"+
    "\0\u0ff1\0\u1026\0\u105b\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u1164"+
    "\0\u1199\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c"+
    "\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4"+
    "\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c"+
    "\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u1765\0\u179a\0\u17cf\0\u1804"+
    "\0\u1839\0\u186e\0\u18a3\0\u18d8\0\u190d\0\u1942\0\u1977\0\u19ac"+
    "\0\u19e1\0\u1a16\0\u1a4b\0\u1a80\0\u1ab5\0\u1aea\0\u1b1f\0\u1b54"+
    "\0\u1b89\0\u1bbe\0\u1bf3\0\u1c28\0\u1c5d\0\u1c92\0\u1cc7\0\u1cfc"+
    "\0\u1d31";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\2\3\1\6\1\7\1\10\2\0"+
    "\1\7\1\11\1\12\1\13\1\3\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\4\1\23\1\24\1\25"+
    "\4\4\1\26\1\4\1\27\1\30\1\4\1\31\5\4"+
    "\1\32\1\33\2\4\1\12\1\34\1\35\1\36\1\37"+
    "\1\40\1\37\1\41\5\42\1\43\6\42\1\44\50\42"+
    "\66\0\2\4\13\0\1\45\36\4\10\0\2\46\1\5"+
    "\1\46\5\0\1\46\5\0\36\46\16\0\1\7\3\0"+
    "\1\7\52\0\3\10\1\47\1\10\1\50\1\10\1\51"+
    "\55\10\13\0\1\52\1\53\41\0\1\37\64\0\1\37"+
    "\7\0\2\4\13\0\1\45\1\4\1\54\20\4\1\55"+
    "\13\4\11\0\2\4\13\0\1\45\4\4\1\56\4\4"+
    "\1\57\24\4\11\0\2\4\13\0\1\45\1\4\1\60"+
    "\34\4\11\0\2\4\13\0\1\45\24\4\1\61\5\4"+
    "\1\62\3\4\11\0\2\4\13\0\1\45\33\4\1\63"+
    "\2\4\11\0\2\4\13\0\1\45\1\4\1\64\6\4"+
    "\1\65\25\4\11\0\2\4\13\0\1\45\14\4\1\66"+
    "\5\4\1\67\13\4\11\0\2\4\13\0\1\45\11\4"+
    "\1\70\24\4\11\0\2\4\13\0\1\45\1\4\1\71"+
    "\1\4\1\72\16\4\1\73\13\4\11\0\2\4\13\0"+
    "\1\45\14\4\1\74\21\4\11\0\2\4\13\0\1\45"+
    "\14\4\1\75\21\4\11\0\2\4\13\0\1\45\6\4"+
    "\1\76\27\4\11\0\2\4\13\0\1\45\1\77\35\4"+
    "\11\0\2\4\13\0\1\45\10\4\1\100\25\4\11\0"+
    "\2\4\13\0\1\45\10\4\1\101\25\4\11\0\2\4"+
    "\13\0\1\45\17\4\1\102\16\4\66\0\1\37\2\0"+
    "\1\37\62\0\1\37\63\0\1\37\1\0\1\37\70\0"+
    "\1\37\5\42\1\0\6\42\1\0\50\42\13\0\1\103"+
    "\52\0\1\104\15\0\36\104\10\0\4\46\5\0\1\46"+
    "\5\0\36\46\10\0\5\50\1\0\2\50\3\0\55\50"+
    "\1\47\3\50\1\105\55\50\5\52\1\0\2\52\3\0"+
    "\52\52\1\0\2\4\13\0\1\45\2\4\1\106\33\4"+
    "\11\0\2\4\13\0\1\45\22\4\1\107\13\4\11\0"+
    "\2\4\13\0\1\45\5\4\1\61\30\4\11\0\2\4"+
    "\13\0\1\45\21\4\1\110\14\4\11\0\2\4\13\0"+
    "\1\45\6\4\1\111\27\4\11\0\2\4\13\0\1\45"+
    "\17\4\1\112\16\4\11\0\2\4\13\0\1\45\32\4"+
    "\1\113\3\4\11\0\2\4\13\0\1\45\1\114\11\4"+
    "\1\115\23\4\11\0\2\4\13\0\1\45\6\4\1\116"+
    "\7\4\1\117\3\4\1\120\13\4\11\0\2\4\13\0"+
    "\1\45\33\4\1\110\2\4\11\0\2\4\13\0\1\45"+
    "\5\4\1\121\30\4\11\0\2\4\13\0\1\45\3\4"+
    "\1\122\32\4\11\0\2\4\13\0\1\45\5\4\1\123"+
    "\30\4\11\0\2\4\13\0\1\45\21\4\1\124\14\4"+
    "\11\0\2\4\13\0\1\45\22\4\1\125\13\4\11\0"+
    "\2\4\13\0\1\45\1\4\1\126\34\4\11\0\2\4"+
    "\13\0\1\45\3\4\1\127\32\4\11\0\2\4\13\0"+
    "\1\45\14\4\1\130\21\4\11\0\2\4\13\0\1\45"+
    "\35\4\1\131\11\0\2\4\13\0\1\45\11\4\1\57"+
    "\24\4\11\0\2\4\13\0\1\45\17\4\1\132\16\4"+
    "\11\0\2\4\13\0\1\45\5\4\1\133\30\4\11\0"+
    "\2\104\14\0\36\104\11\0\2\4\13\0\1\45\3\4"+
    "\1\134\32\4\11\0\2\4\13\0\1\45\11\4\1\135"+
    "\24\4\11\0\2\4\13\0\1\45\1\4\1\61\34\4"+
    "\11\0\2\4\13\0\1\45\7\4\1\136\3\4\1\137"+
    "\4\4\1\140\7\4\1\141\1\142\4\4\11\0\2\4"+
    "\13\0\1\45\22\4\1\143\13\4\11\0\2\4\13\0"+
    "\1\45\1\144\35\4\11\0\2\4\13\0\1\45\3\4"+
    "\1\124\32\4\11\0\2\4\13\0\1\45\3\4\1\145"+
    "\32\4\11\0\2\4\13\0\1\45\1\4\1\120\34\4"+
    "\11\0\2\4\13\0\1\45\23\4\1\146\12\4\11\0"+
    "\2\4\13\0\1\45\10\4\1\147\25\4\11\0\2\4"+
    "\13\0\1\45\10\4\1\150\25\4\11\0\2\4\13\0"+
    "\1\45\2\4\1\151\33\4\11\0\2\4\13\0\1\45"+
    "\6\4\1\61\27\4\11\0\2\4\13\0\1\45\27\4"+
    "\1\152\6\4\11\0\2\4\13\0\1\45\5\4\1\114"+
    "\30\4\11\0\2\4\13\0\1\45\4\4\1\124\31\4"+
    "\11\0\2\4\13\0\1\45\3\4\1\153\32\4\11\0"+
    "\2\4\13\0\1\45\1\4\1\154\34\4\11\0\2\4"+
    "\13\0\1\45\34\4\1\155\1\4\11\0\2\4\13\0"+
    "\1\45\10\4\1\156\25\4\11\0\2\4\13\0\1\45"+
    "\4\4\1\61\31\4\11\0\2\4\13\0\1\45\1\4"+
    "\1\157\34\4\11\0\2\4\13\0\1\45\10\4\1\160"+
    "\25\4\11\0\2\4\13\0\1\45\10\4\1\161\25\4"+
    "\11\0\2\4\13\0\1\45\1\4\1\162\6\4\1\163"+
    "\25\4\11\0\2\4\13\0\1\45\22\4\1\164\13\4"+
    "\11\0\2\4\13\0\1\45\1\4\1\165\34\4\11\0"+
    "\2\4\13\0\1\45\14\4\1\124\21\4\11\0\2\4"+
    "\13\0\1\45\1\4\1\166\34\4\11\0\2\4\13\0"+
    "\1\45\32\4\1\167\3\4\11\0\2\4\13\0\1\45"+
    "\24\4\1\170\11\4\11\0\2\4\13\0\1\45\16\4"+
    "\1\61\17\4\11\0\2\4\13\0\1\45\21\4\1\61"+
    "\14\4\11\0\2\4\13\0\1\45\1\4\1\171\34\4"+
    "\11\0\2\4\13\0\1\45\33\4\1\172\2\4\11\0"+
    "\2\4\13\0\1\45\4\4\1\173\31\4\11\0\2\4"+
    "\13\0\1\45\12\4\1\174\23\4\11\0\2\4\13\0"+
    "\1\45\3\4\1\175\32\4\11\0\2\4\13\0\1\45"+
    "\6\4\1\110\27\4\11\0\2\4\13\0\1\45\10\4"+
    "\1\176\25\4\11\0\2\4\13\0\1\45\11\4\1\177"+
    "\24\4\11\0\2\4\13\0\1\45\14\4\1\200\21\4"+
    "\11\0\2\4\13\0\1\45\21\4\1\201\14\4\11\0"+
    "\2\4\13\0\1\45\16\4\1\150\17\4\11\0\2\4"+
    "\13\0\1\45\4\4\1\202\31\4\11\0\2\4\13\0"+
    "\1\45\10\4\1\171\25\4\11\0\2\4\13\0\1\45"+
    "\14\4\1\120\21\4\11\0\2\4\13\0\1\45\10\4"+
    "\1\203\25\4\11\0\2\4\13\0\1\45\15\4\1\204"+
    "\20\4\11\0\2\4\13\0\1\45\14\4\1\61\21\4"+
    "\11\0\2\4\13\0\1\45\17\4\1\61\16\4\11\0"+
    "\2\4\13\0\1\45\2\4\1\120\33\4\11\0\2\4"+
    "\13\0\1\45\6\4\1\120\27\4\11\0\2\4\13\0"+
    "\1\45\11\4\1\110\24\4\11\0\2\4\13\0\1\45"+
    "\4\4\1\120\31\4\11\0\2\4\13\0\1\45\10\4"+
    "\1\205\25\4\11\0\2\4\13\0\1\45\3\4\1\206"+
    "\32\4\11\0\2\4\13\0\1\45\12\4\1\207\23\4"+
    "\11\0\2\4\13\0\1\45\6\4\1\210\27\4\11\0"+
    "\2\4\13\0\1\45\11\4\1\120\24\4\11\0\2\4"+
    "\13\0\1\45\25\4\1\211\10\4\11\0\2\4\13\0"+
    "\1\45\4\4\1\212\31\4\11\0\2\4\13\0\1\45"+
    "\10\4\1\213\25\4\11\0\2\4\13\0\1\45\14\4"+
    "\1\214\21\4\11\0\2\4\13\0\1\45\25\4\1\61"+
    "\10\4\11\0\2\4\13\0\1\45\1\4\1\215\34\4"+
    "\11\0\2\4\13\0\1\45\12\4\1\110\23\4\11\0"+
    "\2\4\13\0\1\45\1\216\35\4\11\0\2\4\13\0"+
    "\1\45\3\4\1\217\32\4\11\0\2\4\13\0\1\45"+
    "\26\4\1\220\7\4\11\0\2\4\13\0\1\45\11\4"+
    "\1\221\24\4\11\0\2\4\13\0\1\45\17\4\1\222"+
    "\16\4\11\0\2\4\13\0\1\45\1\4\1\223\34\4"+
    "\11\0\2\4\13\0\1\45\1\4\1\224\34\4\11\0"+
    "\2\4\13\0\1\45\6\4\1\225\27\4\11\0\2\4"+
    "\13\0\1\45\1\4\1\226\34\4\11\0\2\4\13\0"+
    "\1\45\15\4\1\227\20\4\11\0\2\4\13\0\1\45"+
    "\3\4\1\230\32\4\11\0\2\4\13\0\1\45\27\4"+
    "\1\61\6\4\11\0\2\4\13\0\1\45\16\4\1\231"+
    "\17\4\11\0\2\4\13\0\1\45\22\4\1\134\13\4"+
    "\11\0\2\4\13\0\1\45\17\4\1\110\16\4\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7526];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\1\11\4\1\1\11\23\1\1\11"+
    "\3\1\1\11\1\1\1\0\3\1\1\11\1\1\1\11"+
    "\27\1\1\11\1\1\1\11\124\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  

  /* user code: */
   
   /**   
    * Constructor.  This must be here because JFlex does not generate a   
    * no-parameter constructor.   
    */   
   public FetalJFlexTokenMaker() {   
   		super();
   } 
     
   public FetalJFlexTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }
  
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    */   
   private void addToken(int tokenType) {   
      addToken(zzStartRead, zzMarkedPos-1, tokenType);   
   }   
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    * @see #addHyperlinkToken(int, int, int)   
    */   
   private void addToken(int start, int end, int tokenType) {   
      int so = start + offsetShift;   
      addToken(zzBuffer, start,end, tokenType, so, false);   
   }   
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param array The character array.   
    * @param start The starting offset in the array.   
    * @param end The ending offset in the array.   
    * @param tokenType The token's type.   
    * @param startOffset The offset in the document at which this token   
    *        occurs.   
    * @param hyperlink Whether this token is a hyperlink.   
    */   
   public void addToken(char[] array, int start, int end, int tokenType,   
                  int startOffset, boolean hyperlink) {   
      super.addToken(array, start,end, tokenType, startOffset, hyperlink);   
      zzStartRead = zzMarkedPos;   
   }   
   
   /**   
    * Returns the text to place at the beginning and end of a   
    * line to "comment" it in a this programming language.   
    *   
    * @return The start and end strings to add to a line to "comment"   
    *         it out.   
    */   
   public String[] getLineCommentStartAndEnd() {   
      return new String[] { "//", null };   
   }   
   
   /**   
    * Returns the first token in the linked list of tokens generated   
    * from <code>text</code>.  This method must be implemented by   
    * subclasses so they can correctly implement syntax highlighting.   
    *   
    * @param text The text from which to get tokens.   
    * @param initialTokenType The token type we should start with.   
    * @param startOffset The offset into the document at which   
    *        <code>text</code> starts.   
    * @return The first <code>Token</code> in a linked list representing   
    *         the syntax highlighted text.   
    */   
   public Token getTokenList(Segment text, int initialTokenType, int startOffset) {   
   
      resetTokenList();   
      this.offsetShift = -text.offset + startOffset;   
   
      // Start off in the proper state.   
      int state = Token.NULL;   
      switch (initialTokenType) {   
                  case Token.COMMENT_MULTILINE:   
            state = MLC;   
            start = text.offset;   
            break;   
   
         /* No documentation comments */   
         default:   
            state = Token.NULL;   
      }   
   
      s = text;   
      try {   
         yyreset(zzReader);   
         yybegin(state);   
         return yylex();   
      } catch (IOException ioe) {   
         ioe.printStackTrace();   
         return new TokenImpl();   
      }   
   
   }   
   
   /**   
    * Refills the input buffer.   
    *   
    * @return      <code>true</code> if EOF was reached, otherwise   
    *              <code>false</code>.   
    */   
   private boolean zzRefill() {   
      return zzCurrentPos>=s.offset+s.count;   
   }   
   
   /**   
    * Resets the scanner to read from a new input stream.   
    * Does not close the old reader.   
    *   
    * All internal variables are reset, the old input stream    
    * <b>cannot</b> be reused (internal buffer is discarded and lost).   
    * Lexical state is set to <tt>YY_INITIAL</tt>.   
    *   
    * @param reader   the new input stream    
    */  
     
   public final void yyreset(Reader reader) {   
      // 's' has been updated.   
      zzBuffer = s.array;   
      /*   
       * We replaced the line below with the two below it because zzRefill   
       * no longer "refills" the buffer (since the way we do it, it's always   
       * "full" the first time through, since it points to the segment's   
       * array).  So, we assign zzEndRead here.   
       */   
      //zzStartRead = zzEndRead = s.offset;   
      zzStartRead = s.offset;   
      zzEndRead = zzStartRead + s.count - 1;   
      zzCurrentPos = zzMarkedPos = s.offset;   
      zzLexicalState = YYINITIAL;   
      zzReader = reader;    
      zzAtEOF  = false;   
   }   
   


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FetalJFlexTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 208) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }



  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
                zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 154: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 155: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { addToken(Token.IDENTIFIER);
            }
          case 19: break;
          case 2: 
            { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
            }
          case 20: break;
          case 3: 
            { addNullToken(); return firstToken;
            }
          case 21: break;
          case 4: 
            { addToken(Token.WHITESPACE);
            }
          case 22: break;
          case 5: 
            { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
            }
          case 23: break;
          case 6: 
            { addToken(Token.OPERATOR);
            }
          case 24: break;
          case 7: 
            { addToken(Token.SEPARATOR);
            }
          case 25: break;
          case 8: 
            { 
            }
          case 26: break;
          case 9: 
            { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
          case 27: break;
          case 10: 
            { addToken(Token.ERROR_NUMBER_FORMAT);
            }
          case 28: break;
          case 11: 
            { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
            }
          case 29: break;
          case 12: 
            { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
          case 30: break;
          case 13: 
            { start = zzMarkedPos-2; yybegin(MLC);
            }
          case 31: break;
          case 14: 
            { addToken(Token.RESERVED_WORD);
            }
          case 32: break;
          case 15: 
            { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
            }
          case 33: break;
          case 16: 
            { addToken(Token.FUNCTION);
            }
          case 34: break;
          case 17: 
            { addToken(Token.ERROR_STRING_DOUBLE);
            }
          case 35: break;
          case 18: 
            { addToken(Token.DATA_TYPE);
            }
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
